### ISSUE TITLE
about camera pose

### ISSUE THREAD

**Issue by anooooob** [cvg/nice-slam#10]
hi, can you explain why the camera pose[:3, 1:2] should be multiply by -1?
e.g. in src/utils/datasets.py 
            c2w[:3, 1] *= -1.0
            c2w[:3, 2] *= -1.0

**Comment by Zzh2000** [comment]
Hi，
we use the camera coordinate similar to NeRF-PyTorch's code, that is X-axis is from left to right, Y-axis is from down to up, Z-axis is from front to back. However, it seems that all the datasets we ran on are using Y-axis from up to down, Z-axis from back to front, so *-1 is needed. However, please note that other datasets may use other camera axis conventions.

**Comment by ckLibra** [comment]
> Hi， we use the camera coordinate similar to NeRF-PyTorch's code, that is X-axis is from left to right, Y-axis is from down to up, Z-axis is from front to back. However, it seems that all the datasets we ran on are using Y-axis from up to down, Z-axis from back to front, so *-1 is needed. However, please note that other datasets may use other camera axis conventions.

If so, why did you just convert the rotation but not also the translation?

**Comment by VladimirYugay** [comment]
@ckLibra did you figure it out?
