### ISSUE TITLE
Data parallelism with pytorch

### ISSUE THREAD

**Issue by mattiapiz** [cvg/nice-slam#102]
Hii, as I read in most of the previous issues, the CUDA out of memory is quite frequent. I encountered the same problem. In my set up I have two GPU Quadro RTX 4000 with 8gb of RAMs. So my question is, is it possible to let use pytorch both the GPUs during the mapping phase, so inside the Mapper.py file? I tried but I didn't find any torch.device() so I don't how Pytorch assign its computation to the specific GPU. I have already tried to split just the Mapping on one GPU and the Tracking on the other one, but got the same error.

**Comment by Zzh2000** [comment]
Hi, actually I also tried running the tracking and mapping on different GPUs before, just need to change the gpu device in the config file, e.g. for tracking cuda:0, for mapping cuda:1.
