### ISSUE TITLE
Demo       Stuck at 16 frames, GPU not working

### ISSUE THREAD

**Issue by glaciomarine** [cvg/nice-slam#103]
INFO: The output folder is output/Demo
INFO: The GT, generated and residual depth/color images can be found under output/Demo/vis/
INFO: The mesh can be found under output/Demo/mesh/
INFO: The checkpoint can be found under output/Demo/ckpt/
Tracking Frame 16:   3%|██▎   

Stuck at 16 frames, GPU not working

**Comment by Zzh2000** [comment]
Hi, please double-check your environment.

**Comment by tyz1030** [comment]
encounting same issue, demo stuck at frame 16. Conda environment built with no issue

**Comment by tyz1030** [comment]
actually this bug is a bit weired. It stuck at certain frames on my desktop, but works just fine on my laptop. which is annoying. Both using ubuntu 22.04 with nvidia 4090 series graphics. Not sure what makes the difference

**Comment by glaciomarine** [comment]
Thanks for your answer. Now I have encountered a new problem. I will encounter two problems when using 2080ti or 3090, one is CUDA out of memory. The other is thread_monitor Resource temporarily unavailable in pthread_create




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zihan ***@***.***&gt;; 
发送时间: 2023年10月18日(星期三) 凌晨2:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cvg/nice-slam] Demo       Stuck at 16 frames, GPU not working (Issue #103)





 
Closed #103 as completed.

**Comment by doginono** [comment]
@glaciomarine How were you able to solve this problem? While trying out the Demo like you, I also got stuck at the 16th frame. I am using an Nvidia GPU: RTX3070
