### ISSUE TITLE
When running 2080ti and 3090, Report an error "a thread_monitor Resource temporarily unavailable in pthread_create occurs"

### ISSUE THREAD

**Issue by glaciomarine** [cvg/nice-slam#105]
Hello, I have two problems with the 2080ti or 3090, one is "CUDA out of memory......", and the other is "thread_monitor Resource temporarily unavailable in pthread_create"

The following is run.py
import argparse
import random

import numpy as np
import torch

import cv2
cv2.setNumThreads(1)

from src import config
from src.NICE_SLAM import NICE_SLAM

import os
os.environ["MKL_NUM_THREADS"] = '4'
os.environ["NUMEXPR_NUM_THREADS"] = '4'
os.environ["OMP_NUM_THREADS"] = '4'

def setup_seed(seed):
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
    random.seed(seed)
    torch.backends.cudnn.deterministic = True

def main():
    # setup_seed(20)
    
    os.environ['OPENBLAS_NUM_THREADS'] = '1'

    parser = argparse.ArgumentParser(
        description='Arguments for running the NICE-SLAM/iMAP*.'
    )
    parser.add_argument('config', type=str, help='Path to config file.')
    parser.add_argument('--input_folder', type=str,
                        help='input folder, this have higher priority, can overwrite the one in config file')
    parser.add_argument('--output', type=str,
                        help='output folder, this have higher priority, can overwrite the one in config file')
    nice_parser = parser.add_mutually_exclusive_group(required=False)
    nice_parser.add_argument('--nice', dest='nice', action='store_true')
    nice_parser.add_argument('--imap', dest='nice', action='store_false')
    parser.set_defaults(nice=True)
    args = parser.parse_args()

    cfg = config.load_config(
        args.config, 'configs/nice_slam.yaml' if args.nice else 'configs/imap.yaml')

    slam = NICE_SLAM(cfg, args)

    slam.run()

if __name__ == '__main__':
    main()

**Comment by Zzh2000** [comment]
On several Ubuntu 3090 I worked on the code is able to run without any problem, but on some operating systems or some versions, it does not work. To debug you can try running it on some other computer. You don't need a specific THREADS configuration I think.
