### ISSUE TITLE
Whether the repository contains training code.

### ISSUE THREAD

**Issue by QQQ300kuai** [cvg/nice-slam#106]
Sorry, I'd like to know if the training code is included in the repository. I want to start training the model again.

**Comment by Zzh2000** [comment]
Sorry, the training code is not included, but it should not be that hard, you can directly replace the MLP class in ConvOccNet with NICE-SLAM's MLP and begin training using the default hyperparameter.

**Comment by Zoey6677** [comment]
> Sorry, I'd like to know if the training code is included in the repository. I want to start training the model again.

@QQQ300kuai Hello, I would also like to try training the model. I'm a beginner, so it's too difficult for me to understand the author's answer. Can you share how you do that? It would be nice to be more detailed. Thank you so much!
