### ISSUE TITLE
About depth image of Replica

### ISSUE THREAD

**Issue by jiatongli2024** [cvg/nice-slam#108]
Thank you for your remarkable work!
Could you please tell me the unit type of your depth map, for example m, cm or mm.
This is the numpy matrix for `./Datasets/Replica/room0/results/depth000064.png`

[[10848 10861 10875 ... 15886 15886 15887]
 [10848 10862 10876 ... 15944 15945 15946]
 [10849 10862 10876 ... 16003 16004 16005]
 ...
 [ 7771  7770  7769 ... 15998 15998 15999]
 [ 7765  7763  7762 ... 15958 15958 15958]
 [ 7758  7756  7755 ... 15918 15918 15918]]

Fathermore, I'm new to indoor reconstruction,would you like to tell me how are your depth maps  defined?

Thank you!

**Comment by Zzh2000** [comment]
Thanks for your interest in our work.
There is a config file in the Replica dataset from the iMAP authors. Usually, for a png depth image,  the value needs to be divided by a certain value e.g. 1000 or 65535 to be transformed to m.
