### ISSUE TITLE
Running SLAM in online mode

### ISSUE THREAD

**Issue by nirmalsnair** [cvg/nice-slam#109]
Thanks for sharing the code!

I've read through the documentation, but couldn't find instructions on running this SLAM in online mode (as it is supposed to). Could you please direct me to the appropriate resource? Thanks.

**Comment by Zzh2000** [comment]
Hi, we mostly evaluate on datasets, if you want to run online with your device attached to the computer, maybe you could try SplaTAM, they provided a demo on their GitHub.
