### ISSUE TITLE
 Use my own RGB-D sequence from Kinect 1.0 or 2.0

### ISSUE THREAD

**Issue by Zoey6677** [cvg/nice-slam#110]
Hi, thank you very much for your great work first.
There are three questions that confuse me.First, can I use my own RGB-D sequence from Kinect 1.0 or 2.0?Second, if so, can this guide in the Readme still work?https://www.open3d.org/docs/release/tutorial/sensor/azure_kinect.html#install-the-azure-kinect-sdk Third,If this guide doesn't work, then what should I do?
Thank you so much!

**Comment by Zzh2000** [comment]
Hi, thanks for your interest in our work. I am not very familiar with Kinect 1.0 or 2.0, the specific procedure for getting the RGB-D frames, might be different, but after getting the frames, the rest would be the same with Kinect Azure.
