### ISSUE TITLE
AutoDL

### ISSUE THREAD

**Issue by Zoey6677** [cvg/nice-slam#112]
Hi~I decided to operate on AutoDL, can you share that? Thank you so much!

By the way, dear Zihan, Do you have a code for pure nice-slam? That is, it does not contain IMAP.Thanks!

**Comment by Zzh2000** [comment]
Hi, sorry, I found out my mirror is no longer available on AutoDL (too long time ago I guess). I don't have the code only containing nice-slam, but you can remove the part for iMAP by finding `for imap*` comments in the code.
