### ISSUE TITLE
Packages Not Found Error

### ISSUE THREAD

**Issue by alpakbaci** [cvg/nice-slam#113]
When I try to create the environment, I get this error. What can I do for this?

ResolvePackageNotFound:
  - _libgcc_mutex==0.1=conda_forge
  - mkl==2021.4.0=h8d4b97c_729
  - dbus==1.13.18=hb2f20db_0
  - glib==2.69.1=h4ff587b_1
  - lcms2==2.12=h3be6417_0
  - lz4-c==1.9.3=h295c915_1
  - fontconfig==2.13.1=h6c09931_0
  - giflib==5.2.1=h7b6447c_0
  - python==3.7.11=h12debd9_0
  - mkl-service==2.4.0=py37h402132d_0
  - matplotlib==3.4.3=py37h06a4308_0
  - cryptography==36.0.0=py37h9ce1e76_0
  - openh264==2.1.1=h780b84a_0
  - matplotlib-base==3.4.3=py37hbbc1b5f_0
  - libuuid==1.0.3=h7f8727e_2
  - mkl_random==1.2.2=py37h219a48f_0
  - zlib==1.2.11=h166bdaf_1014
  - gnutls==3.6.13=h85f3911_1
  - ld_impl_linux-64==2.36.1=hea4e1c9_2
  - cffi==1.15.0=py37hd667e15_1
  - libuv==1.43.0=h7f98852_0
  - libgcc-ng==11.2.0=h1d223b6_14
  - qt==5.9.7=h5867ecd_1
  - pyembree==0.1.6=py37h0da4684_1
  - libtiff==4.2.0=h85742a9_0
  - libwebp-base==1.2.0=h27cfd23_0
  - xz==5.2.5=h516909a_1
  - llvm-openmp==13.0.1=he0ac6c6_1
  - libnsl==2.0.0=h7f98852_0
  - tk==8.6.12=h27826a3_0
  - ncurses==6.3=h9c3ff4c_0
  - embree==2.17.7=ha770c72_1
  - sqlite==3.37.1=h4ff8645_0
  - gst-plugins-base==1.14.0=h8213a91_2
  - libiconv==1.16=h516909a_0
  - openssl==1.1.1n=h166bdaf_0
  - lame==3.100=h7f98852_1001
  - pytorch==1.11.0=py3.7_cuda11.3_cudnn8.2.0_0
  - cudatoolkit==11.3.1=h2bc3f7f_2
  - libzlib==1.2.11=h166bdaf_1014
  - _openmp_mutex==4.5=1_llvm
  - setuptools==61.2.0=py37h89c1867_3
  - mkl_fft==1.3.1=py37h3e078e5_1
  - bzip2==1.0.8=h7f98852_4
  - brotlipy==0.7.0=py37h27cfd23_1003
  - certifi==2021.10.8=py37h06a4308_2
  - tornado==6.1=py37h27cfd23_0
  - libwebp==1.2.0=h89dd481_0
  - ca-certificates==2022.3.29=h06a4308_0
  - libstdcxx-ng==11.2.0=he4da1e4_14
  - ffmpeg==4.3=hf484d3e_0
  - gmp==6.2.1=h58526e2_0
  - pyqt==5.9.2=py37h05f1152_2
  - libpng==1.6.37=h21135ba_2
  - sip==4.19.8=py37hf484d3e_0
  - zstd==1.4.9=haebb681_0
  - libxcb==1.14=h7b6447c_0
  - kiwisolver==1.3.2=py37h295c915_0
  - freetype==2.10.4=h0708190_1
  - expat==2.4.4=h295c915_0
  - tbb==2021.5.0=h4bd325d_0
  - numpy-base==1.21.2=py37h79a1101_0
  - brotli==1.0.9=he6710b0_2
  - pcre==8.45=h295c915_0
  - readline==8.1=h46c0cb4_0
  - nettle==3.6=he412f7d_0
  - gstreamer==1.14.0=h28cd5cc_2
  - libxml2==2.9.12=h03d6c58_0
  - ninja==1.10.2=h4bd325d_1
  - icu==58.2=he6710b0_3
  - libffi==3.3=he6710b0_2
  - pillow==9.0.1=py37h22f2fdc_0
  - jpeg==9b=h024ee3a_2

**Comment by Zzh2000** [comment]
Hi, I tested the `environment.yml` on Ubuntu, if you are using Windows or another OS then the md5 might be different, you could try to remove the md5 and only leave the version info in `environment.yml`.
