### ISSUE TITLE
Trajectory Generation

### ISSUE THREAD

**Issue by Kairui-SHI** [cvg/nice-slam#114]
I quite appreciate your excellent work! And I'm really interested in.

However, I wonder how to generate trajectory of multi-room scenes like apartment, because I learn from your vmap that random trajectory generation seems to be difficult due to considering the collision. But, in your nice-slam video, the apartment trajectory seems random. 

Therefore, I suppose that multi-room scenes trajectory are almost captured images by people? and single room scenes can generate random smooth trajectory from mesh.ply. So multi-room scenes don't have a gt model?

**Comment by Zzh2000** [comment]
Hi, thanks for your interest in our work. Yes, that's true, the multi-room apartment scene is a real capture using Kinect Azure.
