### ISSUE TITLE
marching_cubes error. Possibly no surface extracted from the level set.

### ISSUE THREAD

**Issue by XIAO4579** [cvg/nice-slam#117]
When I ran it on my own dataset,I met this problem.There were no such xxxmesh.ply document in the output folder,and i don't know how to solve it.
![1720603218245](https://github.com/cvg/nice-slam/assets/162464273/3ab800d7-82c3-4a49-825c-93c91b6b2ef5)

**Comment by ning112106** [comment]
Hello, have you solved this problem?
