### ISSUE TITLE
Download url may not working

### ISSUE THREAD

**Issue by Jing-lun** [cvg/nice-slam#13]
Hi @Zzh2000 @pengsongyou, cheers to your great work!

However, when I tried to download some of the demos/inferences, some of the download scripts returned
> HTTP request sent, awaiting response... 403 Forbidden
And it's hard for foreign users to use hecaiyun. 

Would you mind update the url for the files such as: cull_replica_mesh.zip, Demo.zip, etc.

Thanks

**Comment by pengsongyou** [comment]
Hi @Jing-lun sorry for the inconvenience. The server for keeping data is currently down. We are investigating the reason. Will keep you posted.

**Comment by pengsongyou** [comment]
Hi @Jing-lun the issue should be fixed already, please try again.

**Comment by Jing-lun** [comment]
> Hi @Jing-lun the issue should be fixed already, please try again.

Great, thanks for your prompt reply!
