### ISSUE TITLE
Images in mapping_vis shown the model learned nothing

### ISSUE THREAD

**Issue by Lilyo** [cvg/nice-slam#23]
Hi @pengsongyou , 

Thank you for your great work! I've followed the instruction to download apartment data with cmd line
`bash scripts/download_apartment.sh`
then run NICE-SLAM with:
`python -W ignore run.py configs/Apartment/apartment.yaml`

after several iteration, I check the output images in `output/Apartment/mapping_vis/` and I found something weird, please see the image below:

![01700_0030](https://user-images.githubusercontent.com/12732228/181202710-bd733b9c-131a-4985-9a8e-be9edbd55a1c.jpg)

It seems to me that model learned nothing, any idea?

Looking forward to your reply!

**Comment by Zzh2000** [comment]
Hi, 
it is really strange, the visualization should be similar to https://cvg-data.inf.ethz.ch/nice-slam/vis/Apartment.zip . We just run the open-sourced code and upload the visualizations to the server. I think maybe there is some system configuration error that leads to this phenomenon. Could you try to run it on some other machine? You can also check #8,  the code is runnable on Amazon AWS and AutoDL.
