### ISSUE TITLE
Grid Normalization: potential bug at src.utils.Mesher

### ISSUE THREAD

**Issue by youmi-zym** [cvg/nice-slam#26]
Hi,
Thanks for sharing this great work and code. I found the [code in Mesher.py](https://github.com/cvg/nice-slam/blob/master/src/utils/Mesher.py#L160) may contain some potential bugs, please check:
```python
gt_depth = keyframe['depth'].to(device).reshape(1, 1, H, W)          
vgrid = uv.reshape(1, 1, -1, 2)
depth_sample = F.grid_sample(gt_depth, vgrid, padding_mode='zeros', align_corners=True)
depth_sample = depth_sample.reshape(-1)
max_depth = torch.max(depth_sample)
```
Here, vgrid, i.e., uv, is the projected coordinates, while F.grid_sample requires the coordinates to be normalized into [-1, 1]. 
 Therefore, I think it should look like this:
```python
gt_depth = keyframe['depth'].to(device).reshape(1, 1, H, W)          
vgrid = uv.reshape(1, 1, -1, 2)
# normalized to [-1, 1]
vgrid[..., 0] = (vgrid[..., 0] / (W-1) * 2.0 - 1.0)
vgrid[..., 1] = (vgrid[..., 1] / (H-1) * 2.0 - 1.0)
depth_sample = F.grid_sample(gt_depth, vgrid, padding_mode='zeros', align_corners=True)
depth_sample = depth_sample.reshape(-1)
max_depth = torch.max(depth_sample)
```
Please correct me if I'm wrong. Thanks.

**Comment by Zzh2000** [comment]
Hi, 
Thanks a lot! I think you are right. Since this part is only cleaning the mesh to make it nicer, I got careless . Sorry for this bug!
