### ISSUE TITLE
numpy.core._exceptions._ArrayMemoryError: when test Apartment dataset

### ISSUE THREAD

**Issue by Jiazxzx** [cvg/nice-slam#28]
Hi:

Thanks for your nice work !!!

I have successfully test Replica dataset in this repo.
My GPU is RTX 3090 on a remoted Linux server.
However, only when test Apartment, met following error:

> Tracking Frame  48
> 
> Re-rendering loss: 467.40->344.46 camera tensor error: 0.0018->0.0083
> 
> Tracking Frame  49
> 
> Re-rendering loss: 456.63->417.85 camera tensor error: 0.0016->0.0093
> 
> Tracking Frame  50
> 
> Process Process-1:
> Traceback (most recent call last):
>   File "/home/dlr/anaconda3/envs/nice-slam/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
>     self.run()
>   File "/home/dlr/anaconda3/envs/nice-slam/lib/python3.7/multiprocessing/process.py", line 99, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/dlr/Project/nice-slam/src/NICE_SLAM.py", line 283, in coarse_mapping
>     self.coarse_mapper.run()
>   File "/home/dlr/Project/nice-slam/src/Mapper.py", line 606, in run
>     gt_c2w, self.keyframe_dict, self.keyframe_list, cur_c2w=cur_c2w)
>   File "/home/dlr/Project/nice-slam/src/Mapper.py", line 428, in optimize_map
>     idx, joint_iter, cur_gt_depth, cur_gt_color, cur_c2w, self.c, self.decoders)
>   File "/home/dlr/Project/nice-slam/src/utils/Visualizer.py", line 85, in vis
>     gt_color_np = np.clip(gt_color_np, 0, 1)
>   File "<__array_function__ internals>", line 6, in clip
>   File "/home/dlr/anaconda3/envs/nice-slam/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2115, in clip
>     return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs)
>   File "/home/dlr/anaconda3/envs/nice-slam/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
>     return bound(*args, **kwds)
>   File "/home/dlr/anaconda3/envs/nice-slam/lib/python3.7/site-packages/numpy/core/_methods.py", line 160, in _clip
>     um.clip, a, min, max, out=out, casting=casting, **kwargs)
>   File "/home/dlr/anaconda3/envs/nice-slam/lib/python3.7/site-packages/numpy/core/_methods.py", line 113, in _clip_dep_invoke_with_casting
>     return ufunc(*args, out=out, **kwargs)
> numpy.core._exceptions._ArrayMemoryError: Unable to allocate 21.1 MiB for an array with shape (720, 1280, 3) and data type float64

Maybe it's the same problem with #12, but according to it I didn't solve the error. And i'm sorry to create another issue below your project.

I notice there are some "imshow" codes in Visualizer.py. I run NICE-SLAM via remoted Linux server by SSH. Will it cause the issue ？

Thanks for your replying !

**Comment by Zzh2000** [comment]
Hi, 
thanks a lot for your interest in our work! 
The problem is truly strange, we ran the released code on many devices with different GPUs across institutions and did not encounter the same issue. Maybe you can ask [LongruiDong](https://github.com/LongruiDong) in #12 and see how he fixed this problem. I wonder if you are using the Ubuntu system and installed the environment using the conda config file. 
Remote SSH might not work with "imshow" codes in Visualizer.py, maybe you can try X11 forward.
Good luck!
