### ISSUE TITLE
The color result explanation

### ISSUE THREAD

**Issue by Jumponthemoon** [cvg/nice-slam#30]
Hi,i‘m wondering what's the meaning of the color of the result?(Sorry,as a beginner of slam
![image](https://user-images.githubusercontent.com/39290403/187220710-7e4ae8a0-b9e6-4b93-aea7-1ee89521d681.png)

**Comment by Zzh2000** [comment]
Hi, 
it is the normal rendering, maybe you can check this link https://www.google.com.hk/search?q=normal+rendering&oq=normal+rendering&aqs=chrome..69i57j0i512l2j0i131i433i512j0i512l2j0i433i512j0i512l2j0i433i512.3467j1j7&sourceid=chrome&ie=UTF-8
