### ISSUE TITLE
Missing coarse value in the results of NICE-SLAM in Replica checkpoints

### ISSUE THREAD

**Issue by Shelley1214** [cvg/nice-slam#31]
Hi, Thanks for sharing the code!

I've downloaded the results of NICE-SLAM in Replica [here](https://cvg-data.inf.ethz.ch/nice-slam/vis/Replica/) but cannot find the grid_coarse and coarse_decoder values in checkpoints.

Would like to know if you remove those results after consideration, or were those models trained without coarse mapper?

Thanks

**Comment by Zzh2000** [comment]
I just checked I think the results we provided are run with coarse=False in the config file. The purpose of intermediate results is for researchers to check the visualizations (mesh, rendering) without the need to run themselves. We did not think of your use case. Sorry.
