### ISSUE TITLE
KeyFrame Pose Update

### ISSUE THREAD

**Issue by youmi-zym** [cvg/nice-slam#35]
Hi, @Zzh2000:
Thank you for a great job. I find that after BA, the keyframe's pose will be [updated](https://github.com/cvg/nice-slam/blob/master/src/Mapper.py#L531) accordingly, while it doesn't update the pose in [self.estimate_c2w_list](https://github.com/cvg/nice-slam/blob/master/src/Mapper.py#L617).  Will it lead to an inferior result compared to the situation if we also update the pose in [self.estimate_c2w_list](https://github.com/cvg/nice-slam/blob/master/src/Mapper.py#L42)? Since I notice the [eval_ate.py](https://github.com/cvg/nice-slam/blob/master/src/tools/eval_ate.py#L289) uses the self.estimate_c2w_list for evaluation.

**Comment by Zzh2000** [comment]
Hi!
Yeah, I also think if the non-keyframe pose is also updated after BA, the tracking results can be even better.
