### ISSUE TITLE
running on dataset that does not contain gt_camera_poses

### ISSUE THREAD

**Issue by wangm-buaa** [cvg/nice-slam#39]
Hi, thanks for publishing this code.
I want to use only color images and depth maps for scene reconstruction, and I have set the 'gt_camera' parameter in the configure file to False. Unfortunately it seems that the code has to read the poses information for some calculations. How do I solve this problem?

**Comment by Zzh2000** [comment]
Hi, you can check this part in README. https://github.com/cvg/nice-slam#use-your-own-rgb-d-sequence-from-kinect-azure

**Comment by Zoey6677** [comment]
> Hi, thanks for publishing this code. I want to use only color images and depth maps for scene reconstruction, and I have set the 'gt_camera' parameter in the configure file to False. Unfortunately it seems that the code has to read the poses information for some calculations. How do I solve this problem?

 Hi~@wangm-buaa 
Would you mind sharing your dataset with me? Thank you very much!

**Comment by eleftherita** [comment]
> Hi, thanks for publishing this code. I want to use only color images and depth maps for scene reconstruction, and I have set the 'gt_camera' parameter in the configure file to False. Unfortunately it seems that the code has to read the poses information for some calculations. How do I solve this problem?

Hey did you find any solution on that? I have the same problem...could you manage to obtain the reconstruction?
