### ISSUE TITLE
out of memory using V100

### ISSUE THREAD

**Issue by zuixiaosanlang** [cvg/nice-slam#43]
RuntimeError: CUDA out of memory. Tried to allocate 30.00 MiB (GPU 0; 15.78 GiB total capacity; 1.22 GiB already allocated; 8.04 GiB free; 1.32 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Process Process-3:

**Comment by Zzh2000** [comment]
Please double check your environment, as far as I know, my classmates at ZJU and ETH are able to run the code on devices like 2080ti, TITAN X, 3090.
