### ISSUE TITLE
RuntimeError:cuda out of memory and thread_monitor resource temporarily unavailable in pthread_create 

### ISSUE THREAD

**Issue by HDjpf** [cvg/nice-slam#46]
it post 'cuda out of memory'  when I run demo at 350 frames with RTX2080Ti , running with A10 is ok.
it post 'cuda out of memory' or  'thread_monitor resource temporarily unavailable in pthread_create ' when I run apartment at 155 frames with A10, meanwhile one of five python process fork 65 threads when run 155 frames. env config is right 
RuntimeError: CUDA out of memory . Tried to allocate 178.00 MiB(GPU 0; 22.20 GiB total capacity; 402.81 MiB already allocated; 12.79 GiB free; 468.00 MiB reserved in total by PyTorch)

**Comment by Zzh2000** [comment]
Hi, please double-check your environment, as far as I know, my classmates at ZJU and ETH are able to run the code on devices like 2080ti, TITAN X, 3090. We mainly use Linux ubuntu for the experiments, but other distributions like CentOS should also work fine.
