### ISSUE TITLE
Pose Initializing

### ISSUE THREAD

**Issue by CeoiZidung** [cvg/nice-slam#47]
Hi~
Congrats on your great job! I wanna ask how to initialize the pose at the very beginning step, or how can i get the origin pose at the first step in mapping step(cause mapping is ahead of tracking).

**Comment by Zzh2000** [comment]
Hi, 
For the first frame, I initialized as the GT pose's first frame (just to make future mesh alignment automatic during evaluation), but of course, it can also be initialized as the identity matrix. The first frame's mapping must run first, then tracking can begin.
