### ISSUE TITLE
No coarse decorder is used in tracker 

### ISSUE THREAD

**Issue by 00Haocheng** [cvg/nice-slam#49]
Hi, thank you for such an excellent work.
The paper says due to the coarse feature grid, "This extrapolated geometry provides a meaningful signal for the tracking as the camera moves into previously unobserved areas. Making it more robust to sudden frame loss or fast camera movement."
But, When I read the code, I find in Tracker.py, it just use color stage decorde to compute the loss and update camera pose. No coarse grid and decorder is fined. 
I would appreciate it if you could answer this question

**Comment by Zzh2000** [comment]
Hi，
it is true, we did not add this part in our open-sourced code. We spend too much time rewriting the code during code release so we end up with no time for this feature. I hope it is understandable since the experiment for this is in the supplementary.
Best,
Zihan

**Comment by 00Haocheng** [comment]
I got it. It's really hard work. Sincerely thank you for your work and quick reply！

**Comment by TontonTremblay** [comment]
@Zzh2000 would you mind elaborating how this change could impact the performance of the algorithm.

**Comment by Zzh2000** [comment]
Sure. During frame loss (or sudden camera movement) the coarse level's prediction is able to provide useful information for tracking, shown in the supplementary and the last video of the project page. For normal use cases, it will not have too much of a difference.
