### ISSUE TITLE
How to run without multi threading?

### ISSUE THREAD

**Issue by TontonTremblay** [cvg/nice-slam#51]
I am running into a lot of problems with my data where the tracking gets lost and I get errors from the meshing part, from the geometry getting too big or just ray casting throwing errors. I am fine with the errors, but because the treading locks the process, it wont stop on its own and then I need to baby sit the processes. Could you point to me where I could only set on thread so when it crashes it stops the process?

**Comment by Zzh2000** [comment]
I think maybe you can try to kill the other processes if one process has an error. E.g. you can use "try-catch" to cover this line https://github.com/cvg/nice-slam/blob/7af15cc33729aa5a8ca052908d96f495e34ab34c/src/NICE_SLAM.py#L276, and when there is an error in mapping, in "catch" you can use shared memory to send a halt signal to other processes.
