### ISSUE TITLE
Error for function render_batch_ray, sometimes met empty gt_depth

### ISSUE THREAD

**Issue by moyutianque** [cvg/nice-slam#53]
Thanks for the nice project.
I have met one issue. When I was training with scannet scene0000_00, there is an error in file utils/Renderer.py.
```
line 112, in render_batch_ray
    far = torch.clamp(far_bb, 0,  torch.max(gt_depth*1.2))
RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.
```
I use the demo.yaml and only replace the data src to the ScanNet data which is preprocessed following ScanNet/SenseReader 
The running script is 
```
python -W ignore run.py configs/Demo/demo.yaml --nice
```

**Comment by Zzh2000** [comment]
Could you print out the shape and some value of gt_depth?

**Comment by moyutianque** [comment]
Usually, this happens when the gt_depth is an empty tensor with zero in the first dim. But this does not happen at the beginning, it usually happens at some place in the middle of the training, and sometimes it can reach the end. I capture the empty tensor of depth in Mapper.py around line 483
```python
                batch_gt_depth = batch_gt_depth[inside_mask]
                batch_gt_color = batch_gt_color[inside_mask]
```
where batch_gt_depth is empty:

tensor([], device='cuda:0')
For the inputs, I have checked the number of files are matched for color, depth and pose

**Comment by Zzh2000** [comment]
I see, I never encountered this in my experiments, did you modify something? gt_depth is the depth sensor output, which should not be empty.

**Comment by moyutianque** [comment]
I discarded all my changes, but this issue still exists. inside_mask in Mapper around line 477 sometimes are all False values.

**Comment by Zzh2000** [comment]
Sorry, I don't know. I asked others and they also did not encounter this problem. I  would suggest that you don't do the clamping, and directly assign far = far_bb or assign all same values e.g. 5m for far. Then there won't be an error.

**Comment by szgy66** [comment]
I have the same problem. Have you solved it？

**Comment by moyutianque** [comment]
> 

I have not solved

**Comment by moyutianque** [comment]
> I have the same problem. Have you solved it？

I have not solved

**Comment by szgy66** [comment]
> > I have the same problem. Have you solved it？
> 
> I have not solved

I had solved. It may be Render loss too large, you should give the groundtruth

**Comment by lixinhaiyk** [comment]
> > > I have the same problem. Have you solved it？
> > 
> > 
> > I have not solved
> 
> I had solved. It may be Render loss too large, you should give the groundtruth

bro,i also meet this problem,you means the groundtruth is lost for this picture? thanks a lot

**Comment by szgy66** [comment]
> > > > I have the same problem. Have you solved it？
> > > 
> > > 
> > > I have not solved
> > 
> > 
> > I had solved. It may be Render loss too large, you should give the groundtruth
> 
> bro,i also meet this problem,you means the groundtruth is lost for this picture? thanks a lot

Yes, although the code can run only RGB examples, the effect is very poor. When loss is superimposed to a certain extent, the model can no longer be optimized and can only be interrupted. So you need to provide real pose, like TUMD data set, and it works fine.

**Comment by Lijingbohere** [comment]
"So you need to provide real pose, like TUMD data set, and it works fine."What does this phrase mean brother, isn't RGB, depth, pose already passed in when reading data

**Comment by Lijingbohere** [comment]
![image](https://github.com/cvg/nice-slam/assets/75312149/4ac36a3a-01db-45e9-98af-2383ee6bd631)
this is my problem
