### ISSUE TITLE
Are quaternions normalized?

### ISSUE THREAD

**Issue by Minzhao1995** [cvg/nice-slam#56]
Hi,

Thanks for your great work. I notice that quaternions are used when optimizing camera pose. But after optimization, it seems not to normalize the result. Will this cause some problems? For example, the converted rotation matrix may not be an orthogonal matrix.

Thanks!

**Comment by Zzh2000** [comment]
Hi,
Thanks for your interest in our work! 
When converting a quaternion to a rotation matrix, there will be a normalization step, therefore the rotation matrix will be orthogonal.
https://github.com/cvg/nice-slam/blob/7af15cc33729aa5a8ca052908d96f495e34ab34c/src/common.py#L149
