### ISSUE TITLE
Have you evaluated PSNR?

### ISSUE THREAD

**Issue by TwiceMao** [cvg/nice-slam#58]
Have you evaluated PSNR? If so, what was the PSNR roughly? Thank you!

**Comment by Zzh2000** [comment]
Hi，
we did not evaluate PSNR. However, it should not be too hard to get it, I suggest calculating it in this function https://github.com/cvg/nice-slam/blob/7af15cc33729aa5a8ca052908d96f495e34ab34c/src/utils/Visualizer.py#L24, where gt_color and rendered color are available. For extrapolated views, you might need to do more.
