### ISSUE TITLE
Fourier feature mapping

### ISSUE THREAD

**Issue by manurare** [cvg/nice-slam#6]
Hi,

I was wondering why in the fourier feature mapping only ```sin``` is used without ```cos```. In the original paper they use both. Also, why is the gaussian ```_B``` a learnable parameter of the model?
https://github.com/cvg/nice-slam/blob/645b53af3dc95b4b348de70e759943f7228a61ca/src/conv_onet/models/decoder.py#L30

Thanks

**Comment by Zzh2000** [comment]
Hi, 
we use the same encoding as described in iMAP. You can check Section 3.2 of their paper [https://arxiv.org/pdf/2103.12352.pdf](url). In our experiments, we find this way of encoding leads to faster convergence.
