### ISSUE TITLE
No response after running demo

### ISSUE THREAD

**Issue by Qicheng-WANG** [cvg/nice-slam#61]
Hi there,

After I ran the demo, there was no visualization.  What should I do then? Thanks.

![734e6c814a40dac67a110392d96781d](https://user-images.githubusercontent.com/83442982/204707538-c6f6ae13-e0c5-4c03-9ba5-9dfe69394a45.png)

**Comment by Zzh2000** [comment]
https://github.com/cvg/nice-slam/#demo
Finally, run the following command to visualize.
`python visualizer.py configs/Demo/demo.yaml `

Maybe you are using a headless machine？
It is required to use a desktop.

**Comment by Qicheng-WANG** [comment]
I use Xserver to remote display but it still shows nothing. The Xserver is right connected, and it can display commands like xclock and xeyes. I think it is the problem with open3d.
Finally, I have to use my own desktop.

**Comment by Zzh2000** [comment]
Yeah. I also tried before, open3d viewer cannot be correctly displayed by default using Xserver. Maybe special configurations are required.

**Comment by Zoey6677** [comment]
> I use Xserver to remote display but it still shows nothing. The Xserver is right connected, and it can display commands like xclock and xeyes. I think it is the problem with open3d. Finally, I have to use my own desktop.

Hi, @Qicheng-WANG 
What do you mean by "Finally, I have to use my own desktop"? Do you remember how it works? As a beginner, I need your help very much. Thank you!
