### ISSUE TITLE
Run own RGBD dataset with pose

### ISSUE THREAD

**Issue by szgy66** [cvg/nice-slam#64]
Hello!Thank you very much for your project.I tried to replicate your results on my own data set.First, I reproduced the TUMD data according to your README.md instructions, and indeed reconstructed better results.But when I used ORB_SLAM3 to calculate and save the pose information for TUMD and then retrain/visualize, the result was not satisfactory. I use "evo" to compare two tracks as shown below, while I printed the value of c2w in dataset.py(left is the officially provided groundtruth.txt, right is my own). The third image is the ORB computed saved pose.

I really don't understand why the pose is the same height, but the reconstruction results are quite different.
Can you help me? Thanks!
 
![图片1](https://user-images.githubusercontent.com/46223162/209661453-0579d96b-37bc-4ea3-a998-fe62f4952227.png).

![image](https://user-images.githubusercontent.com/46223162/209660965-aa8aa2b5-5524-4f1e-a05e-4c9c7ad6198e.png)

![image_2](https://user-images.githubusercontent.com/46223162/209662220-485838ab-aabf-4885-ac4d-696db596ac31.png)

**Comment by Zzh2000** [comment]
Hi, 
If the poses are nearly the same, there should not be too much reconstruction difference.

**Comment by anghaocheng** [comment]
> Hello!Thank you very much for your project.I tried to replicate your results on my own data set.First, I reproduced the TUMD data according to your README.md instructions, and indeed reconstructed better results.But when I used ORB_SLAM3 to calculate and save the pose information for TUMD and then retrain/visualize, the result was not satisfactory. I use "evo" to compare two tracks as shown below, while I printed the value of c2w in dataset.py(left is the officially provided groundtruth.txt, right is my own). The third image is the ORB computed saved pose.
> 
> I really don't understand why the pose is the same height, but the reconstruction results are quite different. Can you help me? Thanks!
> 
> ![图片1](https://user-images.githubusercontent.com/46223162/209661453-0579d96b-37bc-4ea3-a998-fe62f4952227.png).
> 
> ![image](https://user-images.githubusercontent.com/46223162/209660965-aa8aa2b5-5524-4f1e-a05e-4c9c7ad6198e.png)
> 
> ![image_2](https://user-images.githubusercontent.com/46223162/209662220-485838ab-aabf-4885-ac4d-696db596ac31.png)

Hello, I also encountered this problem when using orb-slam2 to do similar operations. How do you solve it? Is it related to the direction defined by the camera coordinate system in pytorch, which is different from orb-slam

**Comment by 00Haocheng** [comment]
Hello, I also encountered this problem when using orb-slam2 to do similar operations. How do you solve it? Is it related to the direction defined by the camera coordinate system in pytorch, which is different from orb-slam
