### ISSUE TITLE
Meaning of "scale" parameter in nice_slam.yaml config

### ISSUE THREAD

**Issue by yashbhalgat** [cvg/nice-slam#65]
Hi @Zzh2000 , can you please explain what is the purpose of the "scale" parameter in the nice_slam.yaml config [here](https://github.com/cvg/nice-slam/blob/7af15cc33729aa5a8ca052908d96f495e34ab34c/configs/nice_slam.yaml)? Thank you.

**Comment by Zzh2000** [comment]
Hi Yash, 
the "scale" in the config is only for iMAP*. You can check their paper Section 4.1 Implementation Details. " 3D point coordinates are normalised by 1/10 to be close to the [0, 1] range."
