### ISSUE TITLE
How to run visualize code in server?

### ISSUE THREAD

**Issue by rockywind** [cvg/nice-slam#66]
Hi, 
When I run the scripts `python visualizer.py configs/ScanNet/scene0000.yaml --output output/vis/scannet/scans/scene0000_00`, I met the error below.
I ran the script in a server, there is not a monitor. 
![image](https://user-images.githubusercontent.com/14838781/210336541-f6762475-5470-4e10-9711-3f14fc1e562a.png)
![image](https://user-images.githubusercontent.com/14838781/210336607-96e5da93-d46e-4aac-8812-0662225eebe2.png)

**Comment by Zzh2000** [comment]
Hi, please check #61.
