### ISSUE TITLE
Run own dataset

### ISSUE THREAD

**Issue by szgy66** [cvg/nice-slam#67]
Hello. I changed the dataset type from azure to tumrgbd with my own RGBD related sample.yaml.
I get the relevant image pose from ORB_SLAM3, which I have proved to be feasible on the TUM data set, and the reconstruction results are comparable to the official results.
But when I ran my own data, the camera tensor was convergent, but the Re-rendering loss was not.
I kept adjusting the bound and marching_cubes_bound values, but the effect was minimal.
I also looked into other hyperparameters in the relevant.yaml file, but found no useful information about them.
So I would like to ask you to run your own data, those hyperparameters can be adjusted.
thank you!

![image](https://user-images.githubusercontent.com/46223162/211315155-0139e185-caa3-42bb-9c17-81e85c02b380.png)

**Comment by Zzh2000** [comment]
If you really cannot figure out what is wrong. Maybe you can directly follow this tutorial, it is automatic and should not have too many problems. All you have to do is change your format to open3d kinect azure format. https://github.com/cvg/nice-slam#use-your-own-rgb-d-sequence-from-kinect-azure
