### ISSUE TITLE
final_mesh_eval_rec.ply on ScanNet dataset

### ISSUE THREAD

**Issue by youmi-zym** [cvg/nice-slam#68]
Hi @Zzh2000,
Thanks for your excellent work. On the ScanNet dataset, I find there is only the final.ply provided in your document. Frankly speaking, it's already very convenient for us to visualize, and thanks for this convenience. While recently, I also want to evaluate the mesh on ScanNet and have to convert your final.py to final_mesh_eval_rec.ply. As I noticed on the Replica dataset, for evaluation, you will cull, align and finally evaluate the mesh on 2d and 3d metrics. So, does that mean I can get the final_mesh_eval_rec.ply by culling function provided in [cull_mesh.py](https://github.com/cvg/nice-slam/blob/master/src/tools/cull_mesh.py) and then aligning and evaluating functions given in  [eval_recon.py](https://github.com/cvg/nice-slam/blob/master/src/tools/eval_recon.py)? Thanks.

**Comment by Zzh2000** [comment]
I don't think it is a good idea to evaluate on ScanNet, since the ground truth itself has a lot of holes and is not very similar to the actual ground truth. Maybe a visual comparison is enough.
