### ISSUE TITLE
About reconstruction error

### ISSUE THREAD

**Issue by 00Haocheng** [cvg/nice-slam#71]
Thank you very much for such an excellent work. I have some doubts about the evaluation of reconstruction error of imap*.
After imap * reconstruction, I don't know how to evaluate final_ mesh_ eval_ Reconstruction error of rec compared with real room; I tried to import two files into cloudcompare and use the ICP tool, but the result was only to get the rotation matrix. How do you get the specific reconstruction error in the paper

**Comment by Zzh2000** [comment]
Hi, 
You can export the aligned mesh from cloudcompare and then run the python script to evaluate.
https://github.com/cvg/nice-slam#reconstruction-error
