### ISSUE TITLE
torch._C._LinAlgError: cusolver error

### ISSUE THREAD

**Issue by mingming715** [cvg/nice-slam#76]
Hi, I just made the conda environment, and downloaded the Apartment dataset and tried to run NICE-SLAM, with

**python -W ignore run.py configs/Apartment/apartment.yaml**

code, but it shows the error, saying

**torch._C._LinAlgError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnSgetrf( handle, m, n, dA, ldda, static_cast<float*>(dataPtr.get()), ipiv, info)`. This error may appear if the input matrix contains NaN.**

Not sure where this error comes from, any ideas?
![Untitled](https://user-images.githubusercontent.com/46189133/226650456-9d978510-6497-40f7-80c4-2e2596e107f1.png)

**Comment by Zzh2000** [comment]
Hey, it might be that your environment is not very correct. Since others can run without any problem. Please double-check. Good luck!
