### ISSUE TITLE
Question about pre-filtering rays out of bounding box

### ISSUE THREAD

**Issue by heyicheng-never** [cvg/nice-slam#77]
Thanks for your work!
On line 474 in Mapper.py:
`                    t = (self.bound.unsqueeze(0).to(
                        device)-det_rays_o)/det_rays_d
                    t, _ = torch.min(torch.max(t, dim=2)[0], dim=1)
                    inside_mask = t >= batch_gt_depth`
I can't understand the meaning of this code. Can you help explain it? Thanks!

**Comment by Zzh2000** [comment]
Hey, these two lines perform ray-bounding box intersection.

**Comment by heyicheng-never** [comment]
got it. Thanks!
