### ISSUE TITLE
Runtime and threads

### ISSUE THREAD

**Issue by ignotuspeverel** [cvg/nice-slam#81]
Thank you for your amazing work! But I have some problems when I run the code. On the first server I use ~8G GPU with 5 processes to run the apartment dataset. For me training can take up to ten hours, so how long does it usually last? On another server I had problems with threads，I have warnings as thread_monitor Resource temporarily unavailable in pthread_create then the system would stop. How could I fix this problem?

**Comment by Lijingbohere** [comment]
How do you solve the problem of running termination, I have insufficient GPU memory during running and RuntimeError: unable to open shared memory object </torch_2120300_2377371672_458> in read-write mode: No such file or directory (2)
