### ISSUE TITLE
Is there any way to make the code continue to run from where it left off

### ISSUE THREAD

**Issue by Terry10086** [cvg/nice-slam#82]
Thanks for your excellent work! I noticed that there are some checkpoints stored in the output file, such as  **F:\code1\nice-slam\output\Replica\room0\ckpts**. So I wonder if nice-slam provides a way to continue running from a previous checkpoint in case of a crash or unexpected interruption. If not, what's the reason?

**Comment by Zzh2000** [comment]
Hi! Thanks for your interest in our work. It is not provided in the code release, but it is possible to load the checkpoint and start from an intermediate frame with some code writing. PR is highly welcome!
