### ISSUE TITLE
how to undertstand calculating rays for image 

### ISSUE THREAD

**Issue by shaoxiang777** [cvg/nice-slam#83]
Hi, thank you very much for your great work first.

I want to kindly ask how to understand `get_rays` function in [commen.py ](https://github.com/cvg/nice-slam/blob/master/src/common.py)? Is there any theoretical support for it? No matter the math foundation or geometry theory about camera calibration. Actually I don't understand "rays" in depth camera. I would appreciate it if you could explain how it works!
 
I am looking forward to your reply. Thanks a lot in advance!

**Comment by pengsongyou** [comment]
Hi @shaoxiang777, our system is nerf-based, so we follow how NeRF renders a pixel. For the `get_rays` we also simply adapted from the original NeRF repo, see [here](https://github.com/bmild/nerf/blob/master/run_nerf_helpers.py#L123). The "rays" means that the vector from the camera origin to the sampled pixel. To really understand what the `get_rays` is doing, maybe you can first get yourself familiar with the original NeRF paper.
