### ISSUE TITLE
About reproducing nice-slam

### ISSUE THREAD

**Issue by Lijingbohere** [cvg/nice-slam#86]
(nice-slam) lijingbo@Server30901:~/nice-slam-master$ python visualizer.py configs/ScanNet/scene0000.yaml --input  /data_home/home/lijingbo/scene0000_00.zip --output output/vis/scannet/scans/scene0000_00
Traceback (most recent call last):
  File "visualizer.py", line 55, in <module>
    estimate_c2w_list[:, :3, 3] /= scale
NameError: name 'estimate_c2w_list' is not defined

**Comment by Zzh2000** [comment]
Please follow the command in README, passing zip file as input is strange.

**Comment by abdulkarimatrash** [comment]
@Zzh2000  I followed the command in README,  but got the following error:

python visualizer.py configs/Replica/room0_imap.yaml --imap 
Traceback (most recent call last):
  File "visualizer.py", line 55, in <module>
    estimate_c2w_list[:, :3, 3] /= scale
NameError: name 'estimate_c2w_list' is not defined


it seems like visualizer.py expects ckpts to be passed as well ?


but when I ran 
python -W ignore run.py configs/Replica/room0_imap.yaml --imap 

it worked properly. 

any suggestions?
thanks in advance.

**Comment by Zoey6677** [comment]
> @Zzh2000 I followed the command in README, but got the following error:
> 
> python visualizer.py configs/Replica/room0_imap.yaml --imap Traceback (most recent call last): File "visualizer.py", line 55, in estimate_c2w_list[:, :3, 3] /= scale NameError: name 'estimate_c2w_list' is not defined
> 
> it seems like visualizer.py expects ckpts to be passed as well ?
> 
> but when I ran python -W ignore run.py configs/Replica/room0_imap.yaml --imap
> 
> it worked properly.
> 
> any suggestions? thanks in advance.

@random-guest Hi,did you meet the the following error:
python visualizer.py configs/Demo/demo.yaml
Traceback (most recent call last):
  File "visualizer.py", line 36, in <module>
    cfg = config.load_config(
AttributeError: module 'src.conv_onet.config' has no attribute 'load_config'

and I ran
python -W ignore run.py configs/Demo/demo.yaml
the same error

thanks in advance

**Comment by abdulkarimatrash** [comment]
hi @Zoey6677 
No, I didn't.
