### ISSUE TITLE
How can I get the depth l1 value as you listed in paper

### ISSUE THREAD

**Issue by pengchongH** [cvg/nice-slam#88]
Thanks for your nice work.

I tried to evaluate the depth l1 of Relica dataset, and I downloaded the results you provided. Then I got the following results:
accuracy:  2.941982283225373
completion:  1.8669088388589508
completion ratio:  95.0784981250763
Depth L1:  17.809303104877472

The acc and completion looks well, however, I got a bad result in depth l1. 

And I also wonder which mesh you used to get the following results, I have tried final_mesh and final_mesh_rec, I got a higher completion result here.
<img width="1101" alt="image" src="https://github.com/cvg/nice-slam/assets/35575825/2a91b46d-3a7e-4204-85a7-6494997ed2f2">

**Comment by Zzh2000** [comment]
I just tried to directly use the provided command line in README and the provided sample visualization's mesh to evaluate the Depth L1, and it is ~1.7cm, not 17cm for room0, maybe you can double-check. 
As for Acc. and Comp. please check the difference between Table D and Table C in the paper, the code we provided is for Table C.
