### ISSUE TITLE
Question about the time to start tracking

### ISSUE THREAD

**Issue by RickyYXY** [cvg/nice-slam#91]
In your code, both coarse mapper and mapper can change the value "mapping_first_frame", which is a signal to start tracking.
But since you tracker need color decoder, how can you ensure the mapper first change "mapping_first_frame" rather than coarse mapper?
In your code, it is possible that when coarse mapper make mapping_first_frame=1 first, and tracker start tracking frame 0,1. When in frame 1, it is possible that the mapper is still not finish mapping frame 0, which may destroy the tracking. I can't find any code that prevents this situation.
Please check for this, I 'm not sure if I was wrong.
Thks

**Comment by Zzh2000** [comment]
Hi, 
in my previous runs it is not affected, but to ensure a "if not self.coarse_mapper:" statement can be added here https://github.com/cvg/nice-slam/blob/7af15cc33729aa5a8ca052908d96f495e34ab34c/src/Mapper.py#L624
Thanks!
