### ISSUE TITLE
Scannet id scenes, Computation & Runtime Table 4. in Paper.

### ISSUE THREAD

**Issue by abdulkarimatrash** [cvg/nice-slam#92]
Dear authors, 

Thank you for sharing such amazing work!

I have two unclear points that I hope to clarify:

1. I am trying to download scenes from Scan-Net mentioned in your paper, but the scene_id naming is confusing a bit.

for example, in your paper, scenes are mentioned as scene0000 or scene0059, but the instructions for downloading the scenes in Scan-Net need extra two digits for the scan_id (scene[spaceid]_[scanid]). 

for example, for scene0000, it could be scene0000_00, scene0000_01, or scene0000_ 02.

2. Any advice/suggestion/direction to reproduce Table 4 Computation & Runtime results?

Even if not exact, but steps to follow to get such results or a resource to read from to do that? 

Could you please clear that out?

Thank you in advance for your time.

Regards,
Karim,

**Comment by Zzh2000** [comment]
Hi，
Thanks for your interest in our work.
1. We always use sceneXXXX_00
2. For FLOPS it can be manually calculated from the network architecture. For runtime, sum up each iteration's time for mapping or tracking, then take the average.
Hope it helps!

Best,
Zihan
