### ISSUE TITLE
About ScanNet Datasets

### ISSUE THREAD

**Issue by Lijingbohere** [cvg/nice-slam#93]
Thank you so much for making your work public, I reproduced and made changes to your work in recent research, but I couldn't handle the ScanNet dataset, which made my work not go ahead. Would you like to share the processed ScanNet dataset?

**Comment by Zzh2000** [comment]
Hi,
thanks a lot for your interest in our work!
The ScanNet dataset can be downloaded from its website. Please check the instructions in this part https://github.com/cvg/nice-slam#scannet-1. Due to copyright issues, we cannot directly share the dataset download link on our own GitHub.
Best,
Zihan
