### ISSUE TITLE
On visualization issues

### ISSUE THREAD

**Issue by Lijingbohere** [cvg/nice-slam#94]
(nice-slam) linsanity@linsanity-Legion-Y7000P-IAH7:~/下载/NICE-SLAM/nice-slam-master$ python visualizer.py configs/Demo/demo.yaml 
Traceback (most recent call last):
  File "visualizer.py", line 55, in <module>
    estimate_c2w_list[:, :3, 3] /= scale
NameError: name 'estimate_c2w_list' is not defined

**Comment by Zzh2000** [comment]
Please check if you followed all the steps in https://github.com/cvg/nice-slam#demo.
