### ISSUE TITLE
Download url may not working

### ISSUE THREAD

**Issue by onehun** [cvg/nice-slam#95]
Hello!, thank you for your great work!

However, when I tried to download replica dataset using scripts/download_replica.sh, following error occurred 

Resolving cvg-data.inf.ethz.ch (cvg-data.inf.ethz.ch)... 129.132.114.72
Connecting to cvg-data.inf.ethz.ch (cvg-data.inf.ethz.ch)|129.132.114.72|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-28 07:32:04 ERROR 403: Forbidden.

it seems same issue with #13

Would you mind update the url for the file

Thanks

**Comment by Zzh2000** [comment]
Hi, I double checked, the url is working with quite fast download rate. Could you please try again?
