### ISSUE TITLE
Understanding the multi-level grid features

### ISSUE THREAD

**Issue by abdulkarimatrash** [cvg/nice-slam#96]
Dear authors,

thank you for opening your outstanding work!

I am trying to understand how did NICE-SLAM form the features grid.

After sampling points on the ray, I didn't fully get the part of extracting the features using the trilinear interpolation.

what are the plane's specifications that the sampled  3d points are projected to?

Thank you in advance for your reply.

**Comment by Zzh2000** [comment]
Hi, 
thanks a lot for your interest in our work!
There are actually no plane, but 3D feature grids. A 3D point will lie in a voxel and its feature will be the trilinear interpolated feature from its 8 surrounding grid vertices. I think the pipeline figure in the paper can be helpful.
Best,
Zihan
