### ISSUE TITLE
pose in dataset

### ISSUE THREAD

**Issue by sx123456123** [cvg/nice-slam#98]
Hi. what is the role of the poses in the datasets? And can I get the poses from COLMAP?

**Comment by Zzh2000** [comment]
The poses are the ground truth pose provided by the dataset, for evaluation purpose. To run the system, there is no need for gt poses, you can just set all the gt poses to identity.

**Comment by Zoey6677** [comment]
> Hi. what is the role of the poses in the datasets? And can I get the poses from COLMAP?

@sx123456123 
Hi,~
Do you understand what the author says about " you can just set all the gt poses to identity"? As a beginner, I am confused. My understanding is that to modify groundtruth.txt, the format is as follows:
# ground truth trajectory
# file: 'rgbd_dataset_freiburg2_pioneer_360.bag'
# timestamp tx ty tz qx qy qz qw
1311876799.7716 0.0 0.0 0.0 0.0 0.0 0.0 1.0
1311876799.7750 0.0 0.0 0.0 0.0 0.0 0.0 1.0
1311876799.7783 0.0 0.0 0.0 0.0 0.0 0.0 1.0
……
But:
File "/root/onethingai-tmp/nice-slam/src/utils/datasets.py", line 298, in loadtum
(i,j,k)= associations[ix]
IndexError: list index out of range

**Comment by Zoey6677** [comment]
> Hi. what is the role of the poses in the datasets? And can I get the poses from COLMAP?

@sx123456123 
Hi,~
Do you understand what the author says about " you can just set all the gt poses to identity"? As a beginner, I am confused. My understanding is that to modify groundtruth.txt, the format is as follows:
# ground truth trajectory
# file: 'rgbd_dataset_freiburg2_pioneer_360.bag'
# timestamp tx ty tz qx qy qz qw
1311876799.7716 0.0 0.0 0.0 0.0 0.0 0.0 1.0
1311876799.7750 0.0 0.0 0.0 0.0 0.0 0.0 1.0
1311876799.7783 0.0 0.0 0.0 0.0 0.0 0.0 1.0
……
But:
File "/root/onethingai-tmp/nice-slam/src/utils/datasets.py", line 298, in loadtum
(i,j,k)= associations[ix]
IndexError: list index out of range
